# Generated by Django 5.0.4 on 2024-05-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='label',
        ),
        migrations.RemoveField(
            model_name='department',
            name='value',
        ),
        migrations.AddField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('corporateLaw', 'Corporate Law'), ('criminalLaw', 'Criminal Law'), ('familyLaw', 'Family Law'), ('laborLaw', 'Labor Law'), ('intellectualProperty', 'Intellectual Property'), ('taxLaw', 'Tax Law'), ('environmentalLaw', 'Environmental Law'), ('immigrationLaw', 'Immigration Law'), ('realEstateLaw', 'Real Estate Law'), ('healthCareLaw', 'Health Care Law'), ('entertainmentLaw', 'Entertainment Law'), ('bankruptcyLaw', 'Bankruptcy Law'), ('civilRightsLaw', 'Civil Rights Law'), ('internationalLaw', 'International Law'), ('employmentLaw', 'Employment Law'), ('litigation', 'Litigation'), ('antitrustLaw', 'Antitrust Law'), ('cyberLaw', 'Cyber Law')], default=None, max_length=30),
        ),
    ]
