# Generated by Django 5.0.4 on 2024-05-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_remove_department_label_remove_department_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
