# Generated by Django 5.0.4 on 2024-05-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_subscriptionplanmodels_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplanmodels',
            name='billing_period',
            field=models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionplanmodels',
            name='billing_cycle',
            field=models.IntegerField(),
        ),
    ]
