# Generated by Django 5.0.4 on 2024-05-27 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplanmodels_billing_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscription.subscriptionplanmodels'),
            preserve_default=False,
        ),
    ]
