# Generated by Django 5.0.4 on 2024-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptionplan_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
