# Generated by Django 5.0.4 on 2024-05-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customuser_created_at_customuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='document',
            field=models.ImageField(default=None, null=True, upload_to='lawyer_doc/'),
        ),
    ]
