# Generated by Django 5.0.4 on 2024-05-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customuser_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
    ]
