# Generated by Django 5.0.4 on 2024-05-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_department_customuser_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='departments',
            field=models.ManyToManyField(default=None, to='api.department'),
        ),
    ]
