# Generated by Django 4.0 on 2024-06-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_customuser_departments_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='departments',
            field=models.ManyToManyField(blank=True, default=None, to='api.Department'),
        ),
    ]
