# Generated by Django 4.0 on 2024-06-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_customuser_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='lawyer_doc/'),
        ),
    ]
