# Generated by Django 4.0 on 2024-08-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_lawyerprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='document',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='api.Language'),
        ),
    ]
