# Generated by Django 4.0 on 2024-08-30 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_lawyerprofile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.states'),
        ),
    ]
