# Generated by Django 5.1 on 2024-09-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
