# Generated by Django 5.0.4 on 2024-05-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=933443, upload_to='images/'),
            preserve_default=False,
        ),
    ]
