# Generated by Django 5.0.4 on 2024-05-15 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog/', validators=[django.core.validators.FileExtensionValidator(['jpeg'])]),
        ),
    ]
