# Generated by Django 5.0.4 on 2024-05-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
