# Generated by Django 4.0 on 2024-06-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(default='this is a note'),
            preserve_default=False,
        ),
    ]
