# Generated by Django 4.0 on 2024-08-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_report_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='checked',
            new_name='is_listed',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='valid',
        ),
        migrations.AddField(
            model_name='like',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='saved',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
