# Generated by Django 5.1 on 2024-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_blog_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.BooleanField(default=True),
        ),
    ]
