# Generated by Django 5.1 on 2024-09-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_report_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_listed',
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('listed', 'Listed'), ('blocked', 'Blocked')], default='pending', max_length=10),
        ),
    ]
