# Generated by Django 4.0 on 2024-06-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_usercases_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercases',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
