# Generated by Django 4.0 on 2024-06-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_customuser_document'),
        ('case', '0004_usercases_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodels',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.department'),
        ),
        migrations.AlterField(
            model_name='casemodels',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.customuser'),
        ),
        migrations.AlterField(
            model_name='usercases',
            name='case_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cases', to='case.casemodels'),
        ),
        migrations.AlterField(
            model_name='usercases',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cases', to='api.customuser'),
        ),
    ]
