# Generated by Django 4.0 on 2024-06-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_alter_casemodels_department_alter_casemodels_lawyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercases',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
