# Generated by Django 4.0 on 2024-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_alter_case_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
