# Generated by Django 4.0 on 2024-08-30 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_states_alter_lawyerprofile_state'),
        ('case', '0009_case_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.states'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SelectedCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('case_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lawyerprofile')),
            ],
        ),
    ]
