# Generated by Django 5.1 on 2024-08-31 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_allotedcases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allotedcases',
            name='case_model',
        ),
        migrations.RemoveField(
            model_name='allotedcases',
            name='lawyer',
        ),
        migrations.AddField(
            model_name='allotedcases',
            name='selected_case',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alloted_case', to='case.selectedcases'),
            preserve_default=False,
        ),
    ]
