# Generated by Django 4.0 on 2024-08-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='uuid',
        ),
    ]
