# Generated by Django 4.0 on 2024-08-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_scheduling_lawyer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
