# Generated by Django 4.0 on 2024-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_scheduling_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedappointment',
            name='is_transaction_completed',
            field=models.BooleanField(default=False),
        ),
    ]
