# Generated by Django 4.0 on 2024-08-13 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_scheduling_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
