# Generated by Django 4.0 on 2024-08-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_paymentdetails_bookedappointment_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='transaction_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
