# Generated by Django 4.0 on 2024-08-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_paymentdetails_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedappointment',
            name='not_attended',
            field=models.BooleanField(default=False),
        ),
    ]
