# Generated by Django 4.0 on 2024-08-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_bookedappointment_not_attended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedappointment',
            name='not_attended',
        ),
    ]
