# Generated by Django 5.1 on 2024-09-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_bookedappointment_not_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_for',
            field=models.CharField(default='wallet', max_length=50),
            preserve_default=False,
        ),
    ]
