# Generated by Django 4.0 on 2024-09-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_rename_session_date_bookedappointment_session_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='reference_until',
        ),
    ]
