# Generated by Django 5.1 on 2024-09-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_paymentdetails_payment_for'),
        ('wallet', '0002_wallettransactions_payment_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='payment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.paymentdetails'),
        ),
    ]
