# Generated by Django 4.0 on 2024-10-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_withdrawingrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawingrequests',
            name='payment_obj',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallettransactions'),
            preserve_default=False,
        ),
    ]
