# Generated by Django 5.1 on 2024-09-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notifications_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='status',
        ),
    ]
