# Generated by Django 4.0 on 2024-09-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notifications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
